export const RAW_SKUS = [
  // WAFFLE
  { sku: "DMW00111", name: "Mini Waffle Maker", category: "Waffle", color: "Aqua", price: 10.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW00112", name: "Mini Waffle Maker", category: "Waffle", color: "Lilac", price: 10.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DNMWM40003", name: "No Mess Waffle Maker", category: "Waffle", color: "Graphite", price: 49.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1200, status: "CURRENT - CF 2027", notes: "", keyCallout: "No-mess moat catches overflow", sp1: "Drip-free design", sp2: "Non-stick plates", sp3: "5 browning settings", pf1: "Breakfast lovers", pf2: "Busy families", pf3: "", pf4: "", moqColor: 500, moqOrder: 1000, availDate: "2026-01-15", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: true, "Macy's": false }, photo: null },
  { sku: "DIW026GBAQ04", name: "Multimaker", category: "Waffle", color: "Aqua", price: 29.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1200, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DBWM60CGBCM02", name: "Flip Belgian Waffle", category: "Waffle", color: "Cream", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 24.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1200, status: "CURRENT - CF 2027", notes: "Also awarded C6 Endcap", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: true, "Macy's": true }, photo: null },
  { sku: "DMW00201", name: "2pk Holiday Mini Makers", category: "Waffle", color: "Cream", price: 19.99, cost: null, casepack: null, promo: 17.99, marquee: 14.99, timing: "C6 2026", buyType: "DROP IN", placement: "Endcap", doors: null, status: "AWARDED 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // WAFFLE LICENSED
  { sku: "DIW024GBRD04", name: "Multimaker Disney Mickey", category: "Waffle Licensed", color: "Red", price: 34.99, cost: null, casepack: null, promo: 29.99, marquee: 24.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "CURRENT - CF 2027", notes: "", keyCallout: "Disney Mickey waffle shapes", sp1: "Mickey-shaped waffles", sp2: "Non-stick coating", sp3: "Compact design", pf1: "Disney fans", pf2: "Kids", pf3: "Gift givers", pf4: "", moqColor: 500, moqOrder: 1000, availDate: "2026-02-01", packagingCallout: "Disney Licensed", addOn: "", claimBadge: "Disney Official", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: true, "Macy's": false }, photo: null },
  { sku: "DIWD024GBBU4", name: "Multimaker Disney Stitch", category: "Waffle Licensed", color: "Blue", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 29.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DIWDY22CD06", name: "2pk Mickey Heads", category: "Waffle Licensed", color: null, price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW00106", name: "Pooh Mini Maker (Ceramic)", category: "Waffle Licensed", color: "Cream", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Jan 11 - Apr 5", buyType: "DROP IN", placement: "POOH CLUBHOUSE", doors: 250, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW00110", name: "Sweethearts Mini Waffle 'I LUV U'", category: "Waffle Licensed", color: "Purple", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Jan WK 1 - Feb WK 2", buyType: "DROP IN", placement: "SIDE CAP", doors: null, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW00108", name: "Sweethearts Mini Waffle 'XOXO'", category: "Waffle Licensed", color: "Pink", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Jan WK 1 - Feb WK 2", buyType: "DROP IN", placement: "SIDE CAP", doors: null, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW00104", name: "Peeps Bunny Mini Waffle Maker", category: "Waffle Licensed", color: "Pink", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Feb WK 3 - Mar WK 4", buyType: "DROP IN", placement: "SIDE CAP", doors: null, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW00103", name: "Peeps Chick Mini Waffle Maker", category: "Waffle Licensed", color: "Yellow", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Feb WK 3 - Mar WK 4", buyType: "DROP IN", placement: "SIDE CAP", doors: null, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10007", name: "Moana Mini Waffle Maker", category: "Waffle Licensed", color: "Teal", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Mar WK 5 - Sept WK 2", buyType: "DROP IN", placement: "SIDE CAP", doors: 1300, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10008", name: "Buzz Lightyear Mini Waffle Maker", category: "Waffle Licensed", color: "Blue", price: 12.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Mar WK 5 - Sept WK 2", buyType: "DROP IN", placement: "SIDE CAP", doors: 1300, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPNMWV001GR", name: "Peanuts Snoopy Vampire Mini Waffle", category: "Waffle Licensed", color: "Green", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "9/7-10/25", buyType: "DROP IN", placement: "SIDE CAP", doors: 1700, status: "AWARDED", notes: "Separate side cap from Princess/Mickey", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPNMWP001OR", name: "Peanuts Snoopy Jack-O Mini Waffle", category: "Waffle Licensed", color: "Orange", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "9/7-10/25", buyType: "DROP IN", placement: "SIDE CAP", doors: 1700, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10011", name: "Jack Skellington Mini Waffle Maker", category: "Waffle Licensed", color: "Black", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "9/7-10/25", buyType: "DROP IN", placement: "SIDE CAP", doors: 1700, status: "AWARDED 3/24/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPNMW100AL", name: "Peanuts 75th Mini Waffle Maker", category: "Waffle Licensed", color: "Peanuts Print", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "C5", buyType: "DROP IN", placement: "ENDCAP", doors: null, status: "PASSED 3/4/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DIW014GBWH04", name: "Ariel Mini Waffle Maker", category: "Waffle Licensed", color: "Cream", price: 34.99, cost: null, casepack: null, promo: 29.99, marquee: 24.99, timing: "C5", buyType: "DROP IN", placement: "ENDCAP", doors: null, status: "PASSED 3/4/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10012", name: "Belle Mini Waffle Maker", category: "Waffle Licensed", color: "Purple", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "9/7 - End Dec", buyType: "DROP IN", placement: "SIDE CAP", doors: 1300, status: "AWARDED 3/24/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10013", name: "Cinderella Mini Waffle Maker", category: "Waffle Licensed", color: "Pink", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "9/7 - End Dec", buyType: "DROP IN", placement: "SIDE CAP", doors: 1300, status: "AWARDED 3/24/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10014", name: "Mickey Mini Waffle Maker", category: "Waffle Licensed", color: "Blue", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "9/7 - End Dec", buyType: "DROP IN", placement: "SIDE CAP", doors: 1300, status: "AWARDED 3/24/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10016", name: "Mickey Holiday Mini Waffle Maker", category: "Waffle Licensed", color: "Printed Lid", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "11/9-1/10", buyType: "DROP IN", placement: "STOP N SHOP", doors: 250, status: "AWARDED 3/18/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMW10017", name: "Pooh Mini Maker Holiday (Ceramic)", category: "Waffle Licensed", color: "Printed Lid", price: 14.99, cost: null, casepack: null, promo: 12.99, marquee: 9.99, timing: "11/9-1/10", buyType: "DROP IN", placement: "STOP N SHOP", doors: 250, status: "AWARDED 3/18/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // EGG
  { sku: "DEC005TB", name: "Everyday Egg Cooker", category: "Egg", color: "Black", price: 19.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DBBM400GBAQ04", name: "Egg Bite Maker", category: "Egg", color: "Aqua", price: 21.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DECB212GBBK01", name: "Deluxe Egg Cooker", category: "Egg", color: "Black", price: 29.99, cost: null, casepack: null, promo: 24.99, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1200, status: "CURRENT - CF 2027", notes: "", keyCallout: "Cooks 12 eggs at once", sp1: "12-egg capacity", sp2: "Auto shut-off", sp3: "Includes poaching tray", pf1: "Meal preppers", pf2: "Families", pf3: "", pf4: "", moqColor: 300, moqOrder: 600, availDate: "2026-01-01", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: true, Costco: false, Amazon: true, "Macy's": false }, photo: null },
  { sku: "TBD-EGG-EX", name: "Express Egg Cooker", category: "Egg", color: "Cream", price: 19.99, cost: null, casepack: null, promo: 17.99, marquee: 14.99, timing: "Fall 26 - Replace DEC005TB", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "AWARDED FALL RESET ON 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // FROZEN TREATS
  { sku: "DMIC100GBLA04", name: "My Mug Ice Cream Maker", category: "Frozen Treats", color: "Lilac", price: 29.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "CURRENT", notes: "", keyCallout: "Make ice cream in a mug", sp1: "Single-serve portions", sp2: "Ready in minutes", sp3: "No pre-freezing needed", pf1: "Ice cream lovers", pf2: "Dorm rooms", pf3: "Kids", pf4: "", moqColor: 400, moqOrder: 800, availDate: "2026-03-01", packagingCallout: "", addOn: "Recipe book", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: true, "Macy's": false }, photo: null },
  { sku: "DSIM200GBCM04", name: "Deluxe Shaved Ice & Slushy", category: "Frozen Treats", color: "Cream", price: 39.99, cost: null, casepack: null, promo: 29.99, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1700, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DMIC700AQ", name: "Everyday Ice Cream Maker", category: "Frozen Treats", color: "White/Aqua", price: 39.99, cost: null, casepack: null, promo: 29.99, marquee: null, timing: "Summer Treats 2026", buyType: "DROP IN", placement: "Endcap", doors: null, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPIC10001", name: "My Pint (Cream)", category: "Frozen Treats", color: "Cream", price: 19.99, cost: null, casepack: null, promo: 17.99, marquee: 14.99, timing: "C6 2026", buyType: "REPLEN/DROP IN", placement: "IN LINE/ENDCAP", doors: null, status: "AWARDED 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPIC10002", name: "My Pint (Pastel Pink)", category: "Frozen Treats", color: "Pastel Pink", price: 19.99, cost: null, casepack: null, promo: 17.99, marquee: 14.99, timing: "C6 2026", buyType: "DROP IN", placement: "C6 ENDCAP", doors: null, status: "AWARDED 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // TREATS
  { sku: "DAPP150V2AQ04", name: "Fresh Pop 16 Cup", category: "Treats", color: "Aqua", price: 24.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DSSP30001", name: "6QT Smartstore Popcorn", category: "Treats", color: "Aqua", price: 49.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DIM813GBCM04", name: "Multi Plate Treat Maker", category: "Treats", color: "Cream", price: 49.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DCCM00101", name: "Cotton Candy", category: "Treats", color: "Cream", price: 39.99, cost: null, casepack: null, promo: 29.99, marquee: 19.99, timing: "POG Fall 2026", buyType: "REPLEN/DROP IN", placement: "IN LINE/ENDCAP", doors: null, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DCFN00101", name: "Sauce Fountain", category: "Treats", color: "Cream", price: 39.99, cost: null, casepack: null, promo: 29.99, marquee: 19.99, timing: "POG Fall 2026", buyType: "REPLEN/DROP IN", placement: "IN LINE/ENDCAP", doors: null, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DSMR00101", name: "Smores", category: "Treats", color: "Cream", price: 39.99, cost: null, casepack: null, promo: 29.99, marquee: 19.99, timing: "POG Fall 2026", buyType: "REPLEN/DROP IN", placement: "IN LINE/ENDCAP", doors: null, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DHAP10001", name: "Express Popcorn Maker 10 Cup", category: "Treats", color: "Cream", price: 19.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Fall 26 Replace Fresh Pop", buyType: "REPLEN/DROP IN", placement: "IN LINE/ENDCAP", doors: 1800, status: "AWARDED FALL RESET ON 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DSSP30003", name: "6QT Stirring Popcorn Ceramic", category: "Treats", color: "Cream", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 24.99, timing: "Fall 26 Replace Current Aqua", buyType: "REPLEN", placement: "IN LINE", doors: 1800, status: "AWARDED FALL RESET ON 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DFM30001", name: "Fondue Maker", category: "Treats", color: "Cream", price: 39.99, cost: null, casepack: null, promo: null, marquee: 19.99, timing: "Fall 26 replace treat system", buyType: "REPLEN", placement: "IN LINE", doors: 1000, status: "AWARDED FALL RESET ON 3/23/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DAPP15002", name: "Disney Pooh Fresh Pop", category: "Treats", color: "Cream", price: 34.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Jan 11 - Apr 5", buyType: "DROP IN", placement: "POOH CLUBHOUSE", doors: 250, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPC50002", name: "Mickey Popcano", category: "Treats", color: "Red/Black", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 29.99, timing: "C6", buyType: "DROP IN", placement: "Endcap", doors: null, status: "PASSED 3/4/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DPC50001", name: "Jack Popcano", category: "Treats", color: "Black", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 29.99, timing: "C6", buyType: "DROP IN", placement: "Endcap", doors: null, status: "PASSED 3/4/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // MIXING
  { sku: "DTSM370GBCC1", name: "3.5QT Stand Mixer", category: "Mixing", color: "Cream", price: 79.99, cost: null, casepack: null, promo: null, marquee: 39.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1400, status: "CURRENT - CF 2027", notes: "", keyCallout: "Professional results at home", sp1: "3.5 quart stainless bowl", sp2: "6-speed settings", sp3: "Tilt-head design", pf1: "Home bakers", pf2: "Cooking enthusiasts", pf3: "Gift givers", pf4: "", moqColor: 200, moqOrder: 400, availDate: "2026-01-01", packagingCallout: "", addOn: "Dough hook", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: true, "Macy's": true }, photo: null },
  // COOKERS
  { sku: "DRCM20002", name: "Mini Rice Cooker 2 Cup", category: "Cookers", color: "Graphite", price: 24.99, cost: null, casepack: null, promo: null, marquee: null, timing: null, buyType: null, placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DRCM20007", name: "Mini Rice Cooker 2 Cup (Rose)", category: "Cookers", color: "Rose", price: 24.99, cost: null, casepack: null, promo: null, marquee: null, timing: "BTS 2026", buyType: "DROP IN", placement: "Endcap", doors: 200, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DRCM20008", name: "Mini Rice Cooker 2 Cup (Blue)", category: "Cookers", color: "Blue (NEW)", price: 24.99, cost: null, casepack: null, promo: null, marquee: null, timing: "BTS 2026", buyType: "DROP IN", placement: "Endcap", doors: 200, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DRCM20009", name: "Mini Rice Cooker 2 Cup (Taupe)", category: "Cookers", color: "Taupe", price: 24.99, cost: null, casepack: null, promo: null, marquee: null, timing: "BTS 2026", buyType: "DROP IN", placement: "Endcap", doors: 200, status: "AWARDED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // TOAST
  { sku: "DMTO100GBAQ04", name: "Mini Toaster Oven", category: "Toast", color: "Aqua", price: 29.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DVTS501CM", name: "Clear View Toaster", category: "Toast", color: "Cream", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 24.99, timing: null, buyType: "REPLEN", placement: "IN LINE", doors: null, status: "50% Probability", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // BEVERAGE
  { sku: "JB065WH", name: "Citrus Juicer", category: "Beverage", color: "White", price: 19.99, cost: null, casepack: null, promo: 17.99, marquee: 14.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: 1000, status: "CURRENT - CF 2027", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DCBM10SGBCM4", name: "Cold Brew", category: "Beverage", color: null, price: null, cost: null, casepack: null, promo: null, marquee: null, timing: null, buyType: null, placement: null, doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // AIR FRY
  { sku: "DAFG75GBGY01", name: "Flip N Fry 7QT", category: "Air Fry", color: null, price: 99.99, cost: null, casepack: null, promo: null, marquee: null, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DCAF80001", name: "8QT Tasti Crisp Max", category: "Air Fry", color: null, price: 79.99, cost: null, casepack: null, promo: null, marquee: 39.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "dropping fall 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DAFR26001GY", name: "2.6QT Digital Infrared", category: "Air Fry", color: null, price: 69.99, cost: null, casepack: null, promo: 59.99, marquee: 49.99, timing: null, buyType: "REPLEN", placement: "IN LINE", doors: null, status: "PASSED 3/4/26", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DFAFR60001", name: "6QT Digital Infrared", category: "Air Fry", color: null, price: 99.99, cost: null, casepack: null, promo: 79.99, marquee: 59.99, timing: null, buyType: "Replace Flip N Fry", placement: "IN LINE", doors: null, status: "Passed 3/25", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  // GRIDDLE/SKILLET
  { sku: "DEG20CGBCM01", name: "Ceramic Everyday Griddle", category: "Griddle/Skillet", color: "Cream", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: 24.99, timing: "Awarded POG Fall 2025", buyType: "REPLEN", placement: "IN LINE", doors: null, status: "CURRENT - BEING DROPPED SEPT 2026", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
  { sku: "DIG024GBGY04", name: "Flex Press Grill", category: "Griddle/Skillet", color: "Graphite", price: 49.99, cost: null, casepack: null, promo: 39.99, marquee: null, timing: "Q4", buyType: "DROP IN", placement: "Endcap", doors: null, status: "PASSED", notes: "", keyCallout: "", sp1: "", sp2: "", sp3: "", pf1: "", pf2: "", pf3: "", pf4: "", moqColor: null, moqOrder: null, availDate: "", packagingCallout: "", addOn: "", claimBadge: "", pd1: "", pd2: "", pd3: "", pd4: "", pd5: "", retailers: { Target: true, Walmart: false, Costco: false, Amazon: false, "Macy's": false }, photo: null },
];

export const STATUS_CONFIG = {
  "CURRENT - CF 2027": { label: "Active", color: "#059669", bg: "#d1fae5" },
  "CURRENT": { label: "Active", color: "#059669", bg: "#d1fae5" },
  "AWARDED": { label: "Awarded", color: "#0369a1", bg: "#dbeafe" },
  "AWARDED 3/23/26": { label: "Awarded", color: "#0369a1", bg: "#dbeafe" },
  "AWARDED 3/24/26": { label: "Awarded", color: "#0369a1", bg: "#dbeafe" },
  "AWARDED 3/18/26": { label: "Awarded", color: "#0369a1", bg: "#dbeafe" },
  "AWARDED FALL RESET ON 3/23/26": { label: "Awarded", color: "#0369a1", bg: "#dbeafe" },
  "CURRENT - BEING DROPPED SEPT 2026": { label: "Dropping", color: "#b45309", bg: "#fef3c7" },
  "DROPPED SEPT 2026": { label: "Dropped", color: "#9ca3af", bg: "#f3f4f6" },
  "dropping fall 2026": { label: "Dropping", color: "#b45309", bg: "#fef3c7" },
  "PASSED 3/4/26": { label: "Passed", color: "#dc2626", bg: "#fee2e2" },
  "Passed 3/25": { label: "Passed", color: "#dc2626", bg: "#fee2e2" },
  "PASSED": { label: "Passed", color: "#dc2626", bg: "#fee2e2" },
  "50% Probability": { label: "50/50", color: "#7c3aed", bg: "#ede9fe" },
};

export function getStatus(raw) {
  if (!raw) return { label: "Unknown", color: "#9ca3af", bg: "#f3f4f6" };
  return STATUS_CONFIG[raw] || { label: raw.split(" ")[0], color: "#9ca3af", bg: "#f3f4f6" };
}

export const CATEGORIES = [...new Set(RAW_SKUS.map(s => s.category))];
export const RETAILERS_LIST = ["Target", "Walmart", "Costco", "Amazon", "Macy's"];

export const COATING_OPTIONS = [
  { id: "cleanglide", label: "CleanGlide™", full: "CleanGlide™ Ceramic Coating" },
  { id: "truglide",   label: "TruGlide™",   full: "TruGlide™ Ceramic Coating" },
  { id: "cleancoat",  label: "CleanCoating™", full: "CleanCoating™ Ceramic" },
];

export const RETAILER_STATUS_OPTIONS = [
  { value: "",                                label: "— No status" },
  { value: "CURRENT - CF 2027",               label: "Active / Current" },
  { value: "AWARDED",                         label: "Awarded" },
  { value: "CURRENT - BEING DROPPED SEPT 2026", label: "Dropping" },
  { value: "DROPPED SEPT 2026",               label: "Dropped" },
  { value: "PASSED",                          label: "Passed" },
  { value: "50% Probability",                 label: "50/50" },
];

// Normalize each SKU to ensure coating + per-retailer status fields exist
function makeRetailerData(sku) {
  return {
    Target:    { active: !!(sku.retailers?.Target),    status: sku.retailers?.Target    ? (sku.status || "") : "" },
    Walmart:   { active: !!(sku.retailers?.Walmart),   status: "" },
    Costco:    { active: !!(sku.retailers?.Costco),    status: "" },
    Amazon:    { active: !!(sku.retailers?.Amazon),    status: "" },
    "Macy's":  { active: !!(sku.retailers?.["Macy's"]), status: "" },
  };
}

export const SKUS = RAW_SKUS.map(s => ({
  ...s,
  coating: s.coating ?? null,
  retailerData: s.retailerData ?? makeRetailerData(s),
}));

export const CATEGORY_COLORS = {
  "Waffle": "#7F77DD",
  "Waffle Licensed": "#D85A30",
  "Egg": "#1D9E75",
  "Frozen Treats": "#378ADD",
  "Treats": "#EF9F27",
  "Mixing": "#D4537E",
  "Cookers": "#639922",
  "Toast": "#888780",
  "Beverage": "#BA7517",
  "Air Fry": "#E24B4A",
  "Griddle/Skillet": "#0F6E56",
};
